CREATE USER 'bandwidthd'@'%' IDENTIFIED BY 'dbpassword';

GRANT USAGE ON * . * TO 'bandwidthd'@'%' IDENTIFIED BY 'dbpasword' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS `bandwidthd` ;

GRANT ALL PRIVILEGES ON `bandwidthd` . * TO 'bandwidthd'@'%';
